This project was bootstrapped with AWS amplify
see https://docs.amplify.aws/cli/graphql-transformer/overview

##Data Types:
Artists - object that contains artist details and connects to contests
Contests - artist contests for their specific fanbase
ContestAction - ties actions to contests
Enduser - record of users who can take contest actions*
EnduserAction - ties endusers to actions
ActionType - ENUM of types of actions (initially: follow-on-spotify, join-street-team)
Photos - photo records stored in an S3 bucket. connects to artists (one-to-many) and contests (one-to-one)

*note - this only stores basic user data, authentication is handled by AWS Cognito User Pools


## Making Changes to the data structure
If you want to update the graphql schema, you can edit 
    amplify/backend/api/schema.graphql
and run 
    amplify api push
command. This should update the DynamoDB tables and graphql statements.
*Don't mess with the schema.graphql file under amplify/backend/api/build because it gets regenerated by amplify when the api is updated