/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b70a2b71-a654-4e4f-ab52-d60a36e5569a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dfEd0lWf4",
    "aws_user_pools_web_client_id": "7cv82i7h9jjfliojcteib8783t",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://sc7eeyz5onb37cthxqdtfio64y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
